### ISSUE TITLE
handling default manager eid when sending reports

### ISSUE THREAD

**Issue by d-linko** [JHUAPL-DTNMA/dtnma-tools#16]
currently setting manager eid to `"dtn:none"` in `lcc.c` when the eid is not given.
ah proposed fix is  agent could have a text-only configuration of its "current manager" within `nmagent_t` that gets set appropriately from `nmagent_register()`

current work around is including manager eid in `rxmgrs` parameter for `gen_rpts`

**Comment by BrianSipos** [comment]
Closed by #70
