### ISSUE TITLE
ARI handling of integer types in text form

### ISSUE THREAD

**Issue by BrianSipos** [JHUAPL-DTNMA/dtnma-tools#26]
The CACE library needs to handle untyped and typed integer values in text form according to [Section 4.2.1 of the ARI draft](https://www.ietf.org/archive/id/draft-ietf-dtn-ari-02.html#section-4.2.1).

Tests must include positive verification of encoding and decoding specific integer values. This includes alternatives for ARI types BYTE, INT, UINT, VAST, and UVAST and alternatives for encoding using base-2, base-10, base-16 and alternatives for leading signs (including encoded values like "+1" for unsigned types).

**Comment by justinethier** [comment]
Closing, this has been dealt with already by multiple PR's.
