### ISSUE TITLE
ARI handling updates to Ref DA

### ISSUE THREAD

**Issue by mfarina1** [JHUAPL-DTNMA/dtnma-tools#44]
All updates to the reference DA to use the new ARI handling, must be compliant with the AMM doc section 6 and must be completed roughly by mid October since the Agent implementation is the thing on which many other tools depend (i.e. it’s the API for CAMP and what’s being used by ANMS). 

The goal is for Brian (and Nick if he returns) to do the development and Justin to do the test and cleanup

**Comment by BrianSipos** [comment]
Closed by #70
